codecov:
  token: 505aff14-d6f9-498e-aecc-d470e7b60536
  notify:
    require_ci_to_pass: yes

coverage:
  round: up
  range: 0..10
  precision: 2

  status:
    project: yes
    patch: yes
    changes: yes

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: yes        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches: null
