language: python
python:
  - "3.6" 
  # - "3.7.1"

# command to install dependencies
install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -r requirements.txt

# command to run tests
script:
  - python3 -m coverage run -m tests.test_sample
  # - python3 -m coverage combine

after_success:
    - codecov

branches:
  only:
    - master
