language: python

matrix:
    include:
        - dist: xenial
          sudo: true
          python: 3.7

# command to install dependencies
install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -r requirements.txt

# command to run tests
script:
  - python3 -m coverage run -m unittest discover

after_success:
    - codecov

branches:
  only:
    - master
